name: Build Images

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Create tagname
        run: |
          export IMAGENAME=$(echo ${GITHUB_REF##*/} | tr '_' ':')
          echo "IMAGENAME=$IMAGENAME" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: srcml/${{ env.IMAGENAME }}
          platforms: linux/amd64,linux/arm64

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
