name: Build Image Experiment

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Create tagname
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF##*/} | tr '_' ':'
          export IMAGENAME=$(echo ${GITHUB_REF##*/} | tr '_' ':')
          echo $IMAGENAME
          echo "IMAGENAME=$IMAGENAME" >> $GITHUB_ENV

      - name: Create tagname
        run: |
          echo ${{ env.IMAGENAME }}
